on:
  push:
    branches:
    - master
    - development
  pull_request:
    branches:
    - master
    - development
env:
  GO_VERSION: '1.21.5'
jobs:
  Dockerfile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        verbose: true
  Build:
    runs-on: ubuntu-latest
    needs:
        - Dockerfile
    steps:
    - name: podman build
      run: |
        podman build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .
    - name: podman push
      run: |
        podman push ghcr.io/${{ github.repository }}:${{ github.sha }}
