on:
  push:
    branches:
    - master
    - development
  pull_request:
    branches:
    - master
    - development
env:
  GO_VERSION: '1.24.3'
jobs:
  Dockerfile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Lint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        verbose: true
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Run tests
      run: go test ./...
  Build:
    runs-on: ubuntu-latest
    needs:
        - Dockerfile
        - Test
    steps:
    - uses: actions/checkout@v4
    - name: podman build
      run: |
        podman build .
